### PR TITLE
ci: Enhancements to CI and release

### LINKED ISSUE #408: Docker Hub latest tag is 3 months ago
The latest tag looks strange:

https://hub.docker.com/r/andrewgaul/s3proxy/tags

@ansman maybe related to your changed in #382?

### LINKED ISSUE #423: Tag docker images with version numbers
Having version tagged images improves ease of use for administrators by making it clear when a release version of the container is published.

### PR DESCRIPTION
**Pull request by ryanfaircloth**
fixes #408
fixes #423

This PR makes several changes to the CI*
Adds PR lint to ensure conventional commit syntax is used for all PRs see https://www.conventionalcommits.org/
Uses semantic-release tool to review commit log on branch and generate version numbers
Publishes containers (non pr) to ghcr.io
Publishes release containers to hub.docker.com
Completes common tags (versions, sha-1 and ref) on all branches

Notes Unable to test actually publishing containers to dockerhub however this was taken from a similar working project.

Using conventional commit "fix" will increment third dot, "feat" increments second dot. "feat!:" causes a major version. This allows consumers to quickly determine the impact of accepting an upgrade.

Fixes for prior versions can be built by using the tag as the origin and branching to "release/x.y.z" where x.y.z is the tag the fix should be built for. When a fix is applied to the branch it will publish the correct number.

### CODE REVIEW

**Comment by gaul** [comment]
Thank you for your contribution @ryanfaircloth!

**Comment by gaul** [comment]
@ryanfaircloth could you look at the CI failures in https://github.com/gaul/s3proxy/runs/7408534512?check_suite_focus=true ?

**Comment by ryanfaircloth** [comment]
Yes I am away from keyboard a few hours will look when I return to the matrix :)

**Comment by ryanfaircloth** [comment]
@gaul after this PR was merged you removed the semantic-release commands but these were dependencies to properly calculate tags. after your merge #428 you should get clean builds I put back into CI the missing parts

**Pull request merged**
